# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PRODUCT_COPY_FILES += \
    vendor/lenovo/Kraft_T/proprietary/app/qcrilmsgtunnel.apk:system/app/qcrilmsgtunnel.apk \
	vendor/lenovo/Kraft_T/proprietary/app/TimeService.apk:system/app/TimeService.apk \
    vendor/lenovo/Kraft_T/proprietary/bin/adsprpcd:system/bin/adsprpcd \
    vendor/lenovo/Kraft_T/proprietary/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
    vendor/lenovo/Kraft_T/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/lenovo/Kraft_T/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
    vendor/lenovo/Kraft_T/proprietary/bin/dsdnsutil:system/bin/dsdnsutil \
    vendor/lenovo/Kraft_T/proprietary/bin/dun-server:system/bin/dun-server \
    vendor/lenovo/Kraft_T/proprietary/bin/fm_qsoc_patches:system/bin/fm_qsoc_patches \
    vendor/lenovo/Kraft_T/proprietary/bin/fmconfig:system/bin/fmconfig \
    vendor/lenovo/Kraft_T/proprietary/bin/ftmdaemon:system/bin/ftmdaemon \
    vendor/lenovo/Kraft_T/proprietary/bin/garden_app:system/bin/garden_app \
    vendor/lenovo/Kraft_T/proprietary/bin/gpsone_daemon:system/bin/gpsone_daemon \
    vendor/lenovo/Kraft_T/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/lenovo/Kraft_T/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/lenovo/Kraft_T/proprietary/bin/iwconfig:system/bin/iwconfig \
    vendor/lenovo/Kraft_T/proprietary/bin/iwlist:system/bin/iwlist \
    vendor/lenovo/Kraft_T/proprietary/bin/loc_launcher:system/bin/loc_launcher \
    vendor/lenovo/Kraft_T/proprietary/bin/location-mq:system/bin/location-mq \
    vendor/lenovo/Kraft_T/proprietary/bin/lowi-server:system/bin/lowi-server \
    vendor/lenovo/Kraft_T/proprietary/bin/mcDriverDaemon:system/bin/mcDriverDaemon \
    vendor/lenovo/Kraft_T/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
    vendor/lenovo/Kraft_T/proprietary/bin/mm-qcamera-app:system/bin/mm-qcamera-app \
    vendor/lenovo/Kraft_T/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/lenovo/Kraft_T/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/lenovo/Kraft_T/proprietary/bin/n_smux:system/bin/n_smux \
    vendor/lenovo/Kraft_T/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/lenovo/Kraft_T/proprietary/bin/nl_listener:system/bin/nl_listener \
    vendor/lenovo/Kraft_T/proprietary/bin/port-bridge:system/bin/port-bridge \
    vendor/lenovo/Kraft_T/proprietary/bin/ptt_socket_app:system/bin/ptt_socket_app \
    vendor/lenovo/Kraft_T/proprietary/bin/qcom-system-daemon:system/bin/qcom-system-daemon \
    vendor/lenovo/Kraft_T/proprietary/bin/qmiproxy:system/bin/qmiproxy \
    vendor/lenovo/Kraft_T/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/lenovo/Kraft_T/proprietary/bin/qseecom_sample_client:system/bin/qseecom_sample_client \
    vendor/lenovo/Kraft_T/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/lenovo/Kraft_T/proprietary/bin/radish:system/bin/radish \
    vendor/lenovo/Kraft_T/proprietary/bin/rfs_access:system/bin/rfs_access \
    vendor/lenovo/Kraft_T/proprietary/bin/rmnetcli:system/bin/rmnetcli \
    vendor/lenovo/Kraft_T/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/lenovo/Kraft_T/proprietary/bin/sapd:system/bin/sapd \
    vendor/lenovo/Kraft_T/proprietary/bin/SensorCali:system/bin/SensorCali \
    vendor/lenovo/Kraft_T/proprietary/bin/StoreKeybox:system/bin/StoreKeybox \
    vendor/lenovo/Kraft_T/proprietary/bin/subsystem_ramdump:system/bin/subsystem_ramdump \
    vendor/lenovo/Kraft_T/proprietary/bin/thermal-engine:system/bin/thermal-engine \
    vendor/lenovo/Kraft_T/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/lenovo/Kraft_T/proprietary/bin/tinycap:system/bin/tinycap \
    vendor/lenovo/Kraft_T/proprietary/bin/tinypcminfo:system/bin/tinypcminfo \
    vendor/lenovo/Kraft_T/proprietary/bin/tinyplay:system/bin/tinyplay \
    vendor/lenovo/Kraft_T/proprietary/bin/usb_uicc_client:system/bin/usb_uicc_client \
    vendor/lenovo/Kraft_T/proprietary/bin/usbhub:system/bin/usbhub \
    vendor/lenovo/Kraft_T/proprietary/bin/usbhub_init:system/bin/usbhub_init \
    vendor/lenovo/Kraft_T/proprietary/bin/vm_bms:system/bin/vm_bms \
    vendor/lenovo/Kraft_T/proprietary/bin/wcnss_filter:system/bin/wcnss_filter \
    vendor/lenovo/Kraft_T/proprietary/bin/wdsdaemon:system/bin/wdsdaemon \
    vendor/lenovo/Kraft_T/proprietary/bin/xtwifi-client:system/bin/xtwifi-client \
    vendor/lenovo/Kraft_T/proprietary/bin/xtwifi-inet-agent:system/bin/xtwifi-inet-agent \
    vendor/lenovo/Kraft_T/proprietary/etc/quipc.conf:system/etc/quipc.conf \
    vendor/lenovo/Kraft_T/proprietary/etc/sap.conf:system/etc/sap.conf \
    vendor/lenovo/Kraft_T/proprietary/etc/xtwifi.conf:system/etc/xtwifi.conf \
    vendor/lenovo/Kraft_T/proprietary/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:system/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
    vendor/lenovo/Kraft_T/proprietary/etc/acdbdata/MTP/MTP_General_cal.acdb:system/etc/acdbdata/MTP/MTP_General_cal.acdb \
    vendor/lenovo/Kraft_T/proprietary/etc/acdbdata/MTP/MTP_Global_cal.acdb:system/etc/acdbdata/MTP/MTP_Global_cal.acdb \
    vendor/lenovo/Kraft_T/proprietary/etc/acdbdata/MTP/MTP_Handset_cal.acdb:system/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/lenovo/Kraft_T/proprietary/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:system/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
    vendor/lenovo/Kraft_T/proprietary/etc/acdbdata/MTP/MTP_Headset_cal.acdb:system/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
    vendor/lenovo/Kraft_T/proprietary/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:system/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    vendor/lenovo/Kraft_T/proprietary/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb:system/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb \
    vendor/lenovo/Kraft_T/proprietary/etc/acdbdata/QRD/QRD_General_cal.acdb:system/etc/acdbdata/QRD/QRD_General_cal.acdb \
    vendor/lenovo/Kraft_T/proprietary/etc/acdbdata/QRD/QRD_Global_cal.acdb:system/etc/acdbdata/QRD/QRD_Global_cal.acdb \
    vendor/lenovo/Kraft_T/proprietary/etc/acdbdata/QRD/QRD_Handset_cal.acdb:system/etc/acdbdata/QRD/QRD_Handset_cal.acdb \
    vendor/lenovo/Kraft_T/proprietary/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb:system/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb \
    vendor/lenovo/Kraft_T/proprietary/etc/acdbdata/QRD/QRD_Headset_cal.acdb:system/etc/acdbdata/QRD/QRD_Headset_cal.acdb \
    vendor/lenovo/Kraft_T/proprietary/etc/acdbdata/QRD/QRD_Speaker_cal.acdb:system/etc/acdbdata/QRD/QRD_Speaker_cal.acdb \
    vendor/lenovo/Kraft_T/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
    vendor/lenovo/Kraft_T/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
    vendor/lenovo/Kraft_T/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
    vendor/lenovo/Kraft_T/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/lenovo/Kraft_T/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/lenovo/Kraft_T/proprietary/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw \
    vendor/lenovo/Kraft_T/proprietary/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw \
    vendor/lenovo/Kraft_T/proprietary/etc/firmware/a420_pfp.fw:system/etc/firmware/a420_pfp.fw \
    vendor/lenovo/Kraft_T/proprietary/etc/firmware/a420_pm4.fw:system/etc/firmware/a420_pm4.fw \
    vendor/lenovo/Kraft_T/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    vendor/lenovo/Kraft_T/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    vendor/lenovo/Kraft_T/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    vendor/lenovo/Kraft_T/proprietary/etc/firmware/cpp_firmware_v1_4_0.fw:system/etc/firmware/cpp_firmware_v1_4_0.fw \
    vendor/lenovo/Kraft_T/proprietary/etc/firmware/ice40.bin:system/etc/firmware/ice40.bin \
    vendor/lenovo/Kraft_T/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    vendor/lenovo/Kraft_T/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    vendor/lenovo/Kraft_T/proprietary/etc/firmware/Signedrompatch_v20.bin:system/etc/firmware/Signedrompatch_v20.bin \
    vendor/lenovo/Kraft_T/proprietary/etc/firmware/Signedrompatch_v21.bin:system/etc/firmware/Signedrompatch_v21.bin \
    vendor/lenovo/Kraft_T/proprietary/etc/firmware/Signedrompatch_v24.bin:system/etc/firmware/Signedrompatch_v24.bin \
    vendor/lenovo/Kraft_T/proprietary/etc/firmware/Signedrompatch_v30.bin:system/etc/firmware/Signedrompatch_v30.bin \
    vendor/lenovo/Kraft_T/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    vendor/lenovo/Kraft_T/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    vendor/lenovo/Kraft_T/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    vendor/lenovo/Kraft_T/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    vendor/lenovo/Kraft_T/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    vendor/lenovo/Kraft_T/proprietary/etc/firmware/venus.b05:system/etc/firmware/venus.b05 \
    vendor/lenovo/Kraft_T/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    vendor/lenovo/Kraft_T/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt \
    vendor/lenovo/Kraft_T/proprietary/etc/firmware/widevine.b00:system/etc/firmware/widevine.b00 \
    vendor/lenovo/Kraft_T/proprietary/etc/firmware/widevine.b01:system/etc/firmware/widevine.b01 \
    vendor/lenovo/Kraft_T/proprietary/etc/firmware/widevine.b02:system/etc/firmware/widevine.b02 \
    vendor/lenovo/Kraft_T/proprietary/etc/firmware/widevine.b03:system/etc/firmware/widevine.b03 \
    vendor/lenovo/Kraft_T/proprietary/etc/firmware/widevine.mdt:system/etc/firmware/widevine.mdt \
    vendor/lenovo/Kraft_T/proprietary/etc/permissions/android.hardware.sensor.accelerometer.xml:system/etc/permissions/android.hardware.sensor.accelerometer.xml \
    vendor/lenovo/Kraft_T/proprietary/etc/permissions/android.hardware.sensor.compass.xml:system/etc/permissions/android.hardware.sensor.compass.xml \
    vendor/lenovo/Kraft_T/proprietary/etc/permissions/btmultisim.xml:system/etc/permissions/btmultisim.xml \
    vendor/lenovo/Kraft_T/proprietary/etc/permissions/cneapiclient.xml:system/etc/permissions/cneapiclient.xml \
    vendor/lenovo/Kraft_T/proprietary/etc/permissions/com.qrd.wappush.xml:system/etc/permissions/com.qrd.wappush.xml \
    vendor/lenovo/Kraft_T/proprietary/etc/permissions/com.qualcomm.location.vzw_library.xml:system/etc/permissions/com.qualcomm.location.vzw_library.xml \
    vendor/lenovo/Kraft_T/proprietary/etc/permissions/com.qualcomm.location.xml:system/etc/permissions/com.qualcomm.location.xml \
    vendor/lenovo/Kraft_T/proprietary/etc/permissions/com.qualcomm.qti.smartsearch.xml:system/etc/permissions/com.qualcomm.qti.smartsearch.xml \
    vendor/lenovo/Kraft_T/proprietary/etc/permissions/com.qualcomm.wfd.permissions.xml:system/etc/permissions/com.qualcomm.wfd.permissions.xml \
    vendor/lenovo/Kraft_T/proprietary/etc/permissions/interface_permissions.xml:system/etc/permissions/interface_permissions.xml \
    vendor/lenovo/Kraft_T/proprietary/etc/permissions/org.simalliance.openmobileapi.xml:system/etc/permissions/org.simalliance.openmobileapi.xml \
    vendor/lenovo/Kraft_T/proprietary/etc/permissions/qcnvitems.xml:system/etc/permissions/qcnvitems.xml \
    vendor/lenovo/Kraft_T/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/lenovo/Kraft_T/proprietary/framework/qcrilhook.jar:system/framework/qcrilhook.jar \
    vendor/lenovo/Kraft_T/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/lenovo/Kraft_T/proprietary/lib/hw/sensors.msm8916.so:system/lib/hw/sensors.msm8916.so \
    vendor/lenovo/Kraft_T/proprietary/lib/libgps.utils.so:system/lib/libgps.utils.so \
    vendor/lenovo/Kraft_T/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/lenovo/Kraft_T/proprietary/lib/libloc_core.so:system/lib/libloc_core.so \
    vendor/lenovo/Kraft_T/proprietary/lib/libloc_ds_api.so:system/lib/libloc_ds_api.so \
    vendor/lenovo/Kraft_T/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
    vendor/lenovo/Kraft_T/proprietary/lib/liblocation.so:system/lib/liblocation.so \
    vendor/lenovo/Kraft_T/proprietary/lib/libOmxVdecHevc.so:system/lib/libOmxVdecHevc.so \
    vendor/lenovo/Kraft_T/proprietary/lib/librmnetctl.so:system/lib/librmnetctl.so \
    vendor/lenovo/Kraft_T/proprietary/priv-app/com.qualcomm.location.apk:system/priv-app/com.qualcomm.location.apk \
    vendor/lenovo/Kraft_T/proprietary/vendor/etc/calmodule.cfg:system/vendor/etc/calmodule.cfg \
    vendor/lenovo/Kraft_T/proprietary/vendor/lib/drm/libdrmprplugin.so:system/vendor/lib/drm/libdrmprplugin.so \
    vendor/lenovo/Kraft_T/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/lenovo/Kraft_T/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/lenovo/Kraft_T/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/lenovo/Kraft_T/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/lenovo/Kraft_T/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/lenovo/Kraft_T/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/lenovo/Kraft_T/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
    vendor/lenovo/Kraft_T/proprietary/vendor/lib/hw/power.qcom.so:system/vendor/lib/hw/power.qcom.so \
    vendor/lenovo/Kraft_T/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
    vendor/lenovo/Kraft_T/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
    vendor/lenovo/Kraft_T/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so \
    vendor/lenovo/Kraft_T/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    vendor/lenovo/Kraft_T/proprietary/vendor/lib/libacdbmapper.so:system/vendor/lib/libacdbmapper.so \
    vendor/lenovo/Kraft_T/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    vendor/lenovo/Kraft_T/proprietary/vendor/lib/libactuator_dw9718s.so:system/vendor/lib/libactuator_dw9718s.so \
    vendor/lenovo/Kraft_T/proprietary/vendor/lib/libactuator_dw9718s_camcorder.so:system/vendor/lib/libactuator_dw9718s_camcorder.so \
    vendor/lenovo/Kraft_T/proprietary/vendor/lib/libactuator_dw9718s_camera.so:system/vendor/lib/libactuator_dw9718s_camera.so \
    vendor/lenovo/Kraft_T/proprietary/vendor/lib/libactuator_rohm_bu64243gwz.so:system/vendor/lib/libactuator_rohm_bu64243gwz.so \
    vendor/lenovo/Kraft_T/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_camcorder.so:system/vendor/lib/libactuator_rohm_bu64243gwz_camcorder.so \
    vendor/lenovo/Kraft_T/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    vendor/lenovo/Kraft_T/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/lenovo/Kraft_T/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    vendor/lenovo/Kraft_T/proprietary/vendor/lib/libalarmservice_jni.so:system/vendor/lib/libalarmservice_jni.so \
    vendor/lenovo/Kraft_T/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    vendor/lenovo/Kraft_T/proprietary/vendor/lib/libaudioalsa.so:system/vendor/lib/libaudioalsa.so \
    vendor/lenovo/Kraft_T/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so \
    vendor/lenovo/Kraft_T/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/lenovo/Kraft_T/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/lenovo/Kraft_T/proprietary/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
    vendor/lenovo/Kraft_T/proprietary/vendor/lib/libcalmodule_akm.so:system/vendor/lib/libcalmodule_akm.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libcalmodule_common.so:system/vendor/lib/libcalmodule_common.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libcamerahandler_jni.so:system/vendor/lib/libcamerahandler_jni.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libchromatix_gc2355_8916_common.so:system/vendor/lib/libchromatix_gc2355_8916_common.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libchromatix_gc2355_8916_default_video.so:system/vendor/lib/libchromatix_gc2355_8916_default_video.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libchromatix_gc2355_8916_preview.so:system/vendor/lib/libchromatix_gc2355_8916_preview.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libchromatix_imx219_q8n13a_common.so:system/vendor/lib/libchromatix_imx219_q8n13a_common.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libchromatix_imx219_q8n13a_default_video.so:system/vendor/lib/libchromatix_imx219_q8n13a_default_video.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libchromatix_imx219_q8n13a_liveshot.so:system/vendor/lib/libchromatix_imx219_q8n13a_liveshot.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libchromatix_imx219_q8n13a_preview.so:system/vendor/lib/libchromatix_imx219_q8n13a_preview.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libchromatix_imx219_q8n13a_snapshot.so:system/vendor/lib/libchromatix_imx219_q8n13a_snapshot.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libcneconn.so:system/vendor/lib/libcneconn.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libcneqmiutils.so:system/vendor/lib/libcneqmiutils.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libcneutils.so:system/vendor/lib/libcneutils.so \
   vendor/lenovo/Kraft_T/proprietary/vendor/lib/libCommandSvc.so:system/vendor/lib/libCommandSvc.so \
   vendor/lenovo/Kraft_T/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libcsvt_jni.so:system/vendor/lib/libcsvt_jni.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libdisp-aba.so:system/vendor/lib/libdisp-aba.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libDivxDrm.so:system/vendor/lib/libDivxDrm.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/lib-dplmedia.so:system/vendor/lib/lib-dplmedia.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libdpmctmgr.so:system/vendor/lib/libdpmctmgr.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libdpmfdmgr.so:system/vendor/lib/libdpmfdmgr.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libdpmframework.so:system/vendor/lib/libdpmframework.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libdsnetutils.so:system/vendor/lib/libdsnetutils.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libdsucsd.so:system/vendor/lib/libdsucsd.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libExtendedExtractor.so:system/vendor/lib/libExtendedExtractor.so \
   vendor/lenovo/Kraft_T/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
   vendor/lenovo/Kraft_T/proprietary/vendor/lib/libFileMux.so:system/vendor/lib/libFileMux.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libFlacSwDec.so:system/vendor/lib/libFlacSwDec.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libGPTEE.so:system/vendor/lib/libGPTEE.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libHevcSwDecoder.so:system/vendor/lib/libHevcSwDecoder.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libImageRemovalCloningJNI.so:system/vendor/lib/libImageRemovalCloningJNI.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/lib-imscamera.so:system/vendor/lib/lib-imscamera.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/lib-imsdpl.so:system/vendor/lib/lib-imsdpl.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/lib-imsqimf.so:system/vendor/lib/lib-imsqimf.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/lib-imsrcs.so:system/vendor/lib/lib-imsrcs.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/lib-imss.so:system/vendor/lib/lib-imss.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/lib-imsSDP.so:system/vendor/lib/lib-imsSDP.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/lib-imsvt.so:system/vendor/lib/lib-imsvt.so \
   vendor/lenovo/Kraft_T/proprietary/vendor/lib/lib-imsxml.so:system/vendor/lib/lib-imsxml.so \
   vendor/lenovo/Kraft_T/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/liblisten.so:system/vendor/lib/liblisten.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/liblistenhardware.so:system/vendor/lib/liblistenhardware.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/liblistenjni.so:system/vendor/lib/liblistenjni.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/liblistensoundmodel.so:system/vendor/lib/liblistensoundmodel.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/liblistensoundmodel2.so:system/vendor/lib/liblistensoundmodel2.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libloc_ext.so:system/vendor/lib/libloc_ext.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/liblowi_client.so:system/vendor/lib/liblowi_client.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmm-abl.so:system/vendor/lib/libmm-abl.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmm-abl-oem.so:system/vendor/lib/libmm-abl-oem.so \
   vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
   vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmcamera_gc2355_8916.so:system/vendor/lib/libmmcamera_gc2355_8916.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmcamera_imx219_q8n13a.so:system/vendor/lib/libmmcamera_imx219_q8n13a.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmcamera_sony_imx219_eeprom.so:system/vendor/lib/libmmcamera_sony_imx219_eeprom.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmcamera_tuning.so:system/vendor/lib/libmmcamera_tuning.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
   vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
   vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmm-disp-apis.so:system/vendor/lib/libmm-disp-apis.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmm-hdcpmgr.so:system/vendor/lib/libmm-hdcpmgr.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmhttpstack.so:system/vendor/lib/libmmhttpstack.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmi.so:system/vendor/lib/libmmi.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmiipstreammmihttp.so:system/vendor/lib/libmmiipstreammmihttp.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmipstreamaal.so:system/vendor/lib/libmmipstreamaal.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmipstreamnetwork.so:system/vendor/lib/libmmipstreamnetwork.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmipstreamsourcehttp.so:system/vendor/lib/libmmipstreamsourcehttp.so \
   vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmipstreamutils.so:system/vendor/lib/libmmipstreamutils.so \
   vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmparser.so:system/vendor/lib/libmmparser.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmm-qdcm.so:system/vendor/lib/libmm-qdcm.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmQSM.so:system/vendor/lib/libmmQSM.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmQTA.so:system/vendor/lib/libmmQTA.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmrtpdecoder.so:system/vendor/lib/libmmrtpdecoder.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmrtpencoder.so:system/vendor/lib/libmmrtpencoder.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmwfdinterface.so:system/vendor/lib/libmmwfdinterface.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmwfdsinkinterface.so:system/vendor/lib/libmmwfdsinkinterface.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libmmwfdsrcinterface.so:system/vendor/lib/libmmwfdsrcinterface.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libNimsWrap.so:system/vendor/lib/libNimsWrap.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/liboi_sbc_decoder.so:system/vendor/lib/liboi_sbc_decoder.so \
   vendor/lenovo/Kraft_T/proprietary/vendor/lib/libomx_amrdec_sharedlibrary.so:system/vendor/lib/libomx_amrdec_sharedlibrary.so \
   vendor/lenovo/Kraft_T/proprietary/vendor/lib/libomx_amrenc_sharedlibrary.so:system/vendor/lib/libomx_amrenc_sharedlibrary.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libomx_sharedlibrary.so:system/vendor/lib/libomx_sharedlibrary.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libOmxMux.so:system/vendor/lib/libOmxMux.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libprdrmdecrypt.so:system/vendor/lib/libprdrmdecrypt.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libqcom_omx.so:system/vendor/lib/libqcom_omx.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libqc-opt.so:system/vendor/lib/libqc-opt.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libqct_resampler.so:system/vendor/lib/libqct_resampler.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/lenovo/Kraft_T/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    vendor/lenovo/Kraft_T/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libqmi_csvt_srvc.so:system/vendor/lib/libqmi_csvt_srvc.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libquipc_os_api.so:system/vendor/lib/libquipc_os_api.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/lib-rcsimssjni.so:system/vendor/lib/lib-rcsimssjni.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/lib-rcsjni.so:system/vendor/lib/lib-rcsjni.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
   vendor/lenovo/Kraft_T/proprietary/vendor/lib/lib-rtpcommon.so:system/vendor/lib/lib-rtpcommon.so \
   vendor/lenovo/Kraft_T/proprietary/vendor/lib/lib-rtpcore.so:system/vendor/lib/lib-rtpcore.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/lib-rtpdaemoninterface.so:system/vendor/lib/lib-rtpdaemoninterface.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/lib-rtpsl.so:system/vendor/lib/lib-rtpsl.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libsc-a2xx.so:system/vendor/lib/libsc-a2xx.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libscve.so:system/vendor/lib/libscve.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libSHIMDivxDrm.so:system/vendor/lib/libSHIMDivxDrm.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libsregex.so:system/vendor/lib/libsregex.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libsrsprocessing.so:system/vendor/lib/libsrsprocessing.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libsubsystem_control.so:system/vendor/lib/libsubsystem_control.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libSubSystemShutdown.so:system/vendor/lib/libSubSystemShutdown.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libtar.so:system/vendor/lib/libtar.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libthermalioctl.so:system/vendor/lib/libthermalioctl.so \
   vendor/lenovo/Kraft_T/proprietary/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
   vendor/lenovo/Kraft_T/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libtzdrmgenprov.so:system/vendor/lib/libtzdrmgenprov.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libtzplayready.so:system/vendor/lib/libtzplayready.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libulp2.so:system/vendor/lib/libulp2.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libvoice-svc.so:system/vendor/lib/libvoice-svc.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libvt_engine.so:system/vendor/lib/libvt_engine.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libwfdcommonutils.so:system/vendor/lib/libwfdcommonutils.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libwfdhdcpcp.so:system/vendor/lib/libwfdhdcpcp.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libwfdmmsink.so:system/vendor/lib/libwfdmmsink.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libwfdmmsrc.so:system/vendor/lib/libwfdmmsrc.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libwfdmmutils.so:system/vendor/lib/libwfdmmutils.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libwfdnative.so:system/vendor/lib/libwfdnative.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libwfdrtsp.so:system/vendor/lib/libwfdrtsp.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libwfdsm.so:system/vendor/lib/libwfdsm.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libwfduibcinterface.so:system/vendor/lib/libwfduibcinterface.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libwfduibcsink.so:system/vendor/lib/libwfduibcsink.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libwfduibcsinkinterface.so:system/vendor/lib/libwfduibcsinkinterface.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libwfduibcsrc.so:system/vendor/lib/libwfduibcsrc.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libwfduibcsrcinterface.so:system/vendor/lib/libwfduibcsrcinterface.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libwifiscanner.so:system/vendor/lib/libwifiscanner.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libxt_native.so:system/vendor/lib/libxt_native.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libxtadapter.so:system/vendor/lib/libxtadapter.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libxtwifi_ulp_adaptor.so:system/vendor/lib/libxtwifi_ulp_adaptor.so \
	vendor/lenovo/Kraft_T/proprietary/vendor/lib/libxtwifi_zpp_adaptor.so:system/vendor/lib/libxtwifi_zpp_adaptor.so \
